services:
  dbpostgres:
    image: postgres:latest
    container_name: postgres

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3.10.7-management

  auth_wab_api:
    image: auth_wab_api
    build:
      context: .
      dockerfile: services/auth_service/deploy/Dockerfile

  database_wab_api:
    image: database_wab_api
    build:
      context: .
      dockerfile: services/database_service/deploy/Dockerfile

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
