services:

  catalogdb:
    image: mongo:latest

  authdb:
    image: postgres:latest
    container_name: postgres_auth

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:latest

  auth_api:
    image: auth_api
    build:
      context: .
      dockerfile: services/auth_service/deploy/Dockerfile

  mailing:
    image: mailing
    build:
      context: .
      dockerfile: services/mailing_service/deploy/Dockerfile

  catalog_api:
    image: catalog_api
    build:
      context: .
      dockerfile: services/catalog_service/deploy/Dockerfile

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:
