services:

  dbmongo_catalog_service:
    image: mongo:latest

  dbpostgres_auth:
    image: postgres:latest
    container_name: postgres_auth

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:latest

  auth_wab_api:
    image: auth_wab_api
    build:
      context: .
      dockerfile: services/auth_service/deploy/Dockerfile

  mailing_service:
    image: mailing_service
    build:
      context: .
      dockerfile: services/mailing_service/deploy/Dockerfile

  catalog_web_api:
    image: catalog_web_api
    build:
      context: .
      dockerfile: services/catalog_service/deploy/Dockerfile

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:
