services:

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  dbpostgres_auth:
    env_file:
      - infrastructure/postgres/env/auth_service.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ESBlogAuth"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"
    networks:
      - traefik-proxy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  rabbitmq:
    hostname: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
    env_file:
      - infrastructure/rabbitMQ/env/dev.env
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
      - RRABBITMQ_FEATURE_FLAGS=stream_single_active_consumer
    networks:
      - traefik-proxy

  auth_wab_api:
    env_file:
      - services/auth_service/deploy/env/dev.env
    depends_on:
      - dbpostgres_auth
      - rabbitmq
    ports:
      - "8000:8000"
    networks:
      - traefik-proxy


networks:
  traefik-proxy:
    name: traefik-proxy
    external: true
