#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: auth-deployment
#  labels:
#    app: auth-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: auth-deployment
#  template:
#    metadata:
#      labels:
#        app: auth-deployment
#    spec:
#      containers:
#      - name: auth-deployment
#        image: BackendPet/auth-deployment
#        ports:
#        - containerPort: 8000
#
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: auth-service
#spec:
#  selector:
#    app: auth-deployment
#  ports:
#  - port: 8000
#    targetPort: 8000
#  type: LoadBalancer
